using RoLauncher.Desktop;
using System.Text.Json;

if (!CookieBatch.Parse(" first\r\n\r\nsecond\nfirst\rthird ").SequenceEqual(new[] { "first", "second", "third" }) || CookieBatch.Parse(" \r\n").Length != 0)
    throw new Exception("Cookie batches must trim lines, ignore blanks, and deduplicate without changing cookie contents.");

int passed = 0;
void Check(bool condition, string name)
{
    if (!condition) throw new Exception(name);
    passed++;
}
var account = new Account("123", "sample", "My account", new Target(1818, null, null), true, "running", new ProcessInfo(1234), 0, null);
var draft = EditorDraft.From(account);
Check(draft.TryTarget(out var target, out _) && target!.PlaceId == 1818, "Existing targets round-trip.");
draft.Place = "unfinished";
Check(!draft.TryTarget(out _, out _), "An incomplete draft cannot replace a saved destination.");
draft.Place = "0";
Check(!draft.TryTarget(out _, out _), "Place zero is invalid.");
draft.Place = "1818";
draft.Job = "not-a-uuid";
Check(!draft.TryTarget(out _, out _), "Invalid job IDs stay unsaved.");
draft.Job = Guid.NewGuid().ToString();
Check(draft.TryTarget(out target, out _) && target!.JobId == draft.Job, "Specific server target.");
draft.Private = "https://www.roblox.com/games/1818?privateServerLinkCode=ABC";
Check(!draft.TryTarget(out _, out _), "Conflicting destinations are rejected.");
draft.Job = "";
Check(draft.TryTarget(out target, out _) && target!.PrivateServerLink == draft.Private, "Private server target.");
draft.Private = "https://www.roblox.com/games/999?privateServerLinkCode=ABC";
Check(!draft.TryTarget(out _, out _), "Private link must match place.");
draft.Private = "https://evil.example/games/1818?privateServerLinkCode=ABC";
Check(!draft.TryTarget(out _, out _), "External links are rejected.");
draft.Private = "https://www.roblox.com/share?code=ABC&type=Server";
Check(draft.TryTarget(out _, out _), "Share server links are supported.");
draft.Private = "https://www.roblox.com/share?code=ABC&type=Experience";
Check(!draft.TryTarget(out _, out _), "Non-server shares are rejected.");
var row = new AccountRow(account);
Check(row.Destination == "Place 1818", "Account game label falls back to the place number.");
row.SetGameName("Sample experience");
Check(row.Destination == "Sample experience", "Account game label uses resolved metadata.");
row.Update(account with { Status = "stopped" });
Check(row.Destination == "Sample experience", "Status polling retains resolved game metadata.");
row.Update(account with { Target = new Target(999, null, null) });
Check(row.Destination == "Place 999", "Changing a destination discards the previous game's label.");
row.Update(account with { Target = null });
Check(row.Destination == "Choose a game", "An account without a destination prompts game selection.");
row.Update(account);

Check(AccountFilter.Matches(account, " MY ACCOUNT ", "", ""), "Search ignores case and surrounding whitespace.");
Check(AccountFilter.Matches(account, "@SAMP", "running", "on"), "Search matches username with status and rejoin filters.");
Check(!AccountFilter.Matches(account, "missing", "", ""), "Unmatched names are excluded.");
Check(!AccountFilter.Matches(account, "sample", "stopped", ""), "Status combines with search.");
Check(!AccountFilter.Matches(account, "", "running", "off"), "Rejoin combines with status.");
Check(AccountFilter.Matches(account with { Status = "unknown" }, "", "unknown", ""), "Unknown status can be filtered.");
bool updated = false;
row.PropertyChanged += (_, _) => updated = true;
row.Update(account with { Status = "needs_attention", AutoRecovery = false, Alias = "Updated" });
Check(updated && row.Status == "Needs attention" && row.Rejoin == "Off" && row.Alias == "Updated", "Rows update in place, preserving selection identity.");
var streakRow = new AccountRow(account with { RunningSince = DateTimeOffset.UtcNow.AddHours(-2), LongestStreakSeconds = 9000, Status = "reconnecting" });
Check(streakRow.RunningSeconds >= 7200 && streakRow.LongestSeconds == 9000, "Reconnect time counts without replacing a longer saved streak.");
Check(streakRow.RunningTime.StartsWith("2h") && streakRow.LongestOnline == "2h 30m 0s", "Rows show running time and longest online.");
streakRow.Update(account with { LongestStreakSeconds = 9000 });
Check(streakRow.RunningTime == "—" && streakRow.LongestOnline == "2h 30m 0s", "Stopped accounts retain their best streak.");
Check(AccountRow.FormatDuration(90061) == "1d 1h 1m", "Long streaks include days.");
var options = new JsonSerializerOptions { PropertyNamingPolicy = JsonNamingPolicy.SnakeCaseLower, PropertyNameCaseInsensitive = true };
var snapshot = JsonSerializer.Deserialize<Snapshot>("""{"accounts":[{"id":"1","username":"name","alias":"alias","target":{"place_id":1818,"job_id":null,"private_server_link":null},"auto_recovery":true,"status":"running","process":{"pid":999},"failures":2,"last_error":null}],"network_suspended":false,"compatibility":"test"}""", options)!;
Check(snapshot.Accounts[0].Process!.Pid == 999 && snapshot.Accounts[0].Target!.PlaceId == 1818, "Rust account schema deserializes correctly.");
var discord = JsonSerializer.Deserialize<DiscordView>("""{"enabled":false,"configured":true,"notify_recovery":true,"delivery_status":"saved","recent":[{"timestamp":"2026-10-05T00:00:00Z","account":"name","title":"Test","message":"message","place_id":1818}]}""", options)!;
Check(discord.Recent.Length == 1 && discord.Recent[0].Title == "Test", "Discord history uses Rust's recent schema.");
var bulk = new BulkDraft { ApplyGroup = true, Group = "Team", Fields = new() { Place = "invalid", Alias = "" } };
Check(bulk.TryPatch(out var patch, out _) && patch.Count == 1 && (string)patch["group"]! == "Team", "Unchecked mixed fields remain unchanged and are not validated.");
bulk.ApplyTarget = true;
Check(!bulk.TryPatch(out _, out _), "Bulk invalid destination rejects the whole draft before saving.");
bulk.ClearTarget = true;
Check(bulk.TryPatch(out patch, out _) && patch.ContainsKey("clear_target") && !patch.ContainsKey("target"), "Bulk destination clear is explicit.");
bulk.ApplyTarget = false; bulk.Group = "";
Check(bulk.TryPatch(out patch, out _) && (string)patch["group"]! == "", "Blank applied group removes membership.");
bulk.ApplyAlias = true; bulk.Fields.Alias = "Team {index} ({username})";
Check(bulk.TryPatch(out patch, out _) && (string)patch["alias"]! == bulk.Fields.Alias, "Alias patterns reach the backend for per-account expansion.");
bulk.ApplyRejoin = true; bulk.Rejoin = false; bulk.ApplyFallback = true; bulk.Fallback = "pause";
Check(bulk.TryPatch(out patch, out _) && (bool)patch["auto_recovery"]! == false && (string)patch["fallback_policy"]! == "pause", "Explicit false and pause policy are preserved.");
Check(!new BulkDraft().TryPatch(out _, out _), "Empty bulk edits require an Apply setting.");
var retrying = new AccountRow(account with { Status = "backoff", NextRetry = DateTimeOffset.UtcNow.AddMinutes(1), DesiredRunning = true });
Check(retrying.CanRetry && retrying.Retry.Contains("Next retry"), "Scheduled retries expose a countdown and Retry now.");
retrying.Update(retrying.Account with { RecoveryReason = "RateLimit" });
Check(!retrying.CanRetry, "Rate-limit cooldown disables Retry now.");
await UpdateDownloadTests.RunAsync(Check);
Console.WriteLine($"{passed} desktop model/editor/update checks passed.");
